- name: install smbd-smb1 defaults
  template:
    src: templates/default.j2
    dest: /etc/default/smbd-smb1
    mode: '0644'
    owner: root
    group: root
- name: install smbd-smb1 systemd unit
  template:
    src: templates/smbd-smb1.service.j2
    dest: /etc/systemd/system/smbd-smb1.service
    mode: '0644'
    owner: root
    group: root
  notify: systemd
- name: install nmbd-smb1 systemd unit
  template:
    src: templates/nmbd-smb1.service.j2
    dest: /etc/systemd/system/nmbd-smb1.service
    mode: '0644'
    owner: root
    group: root
  notify: systemd
- name: install samba legacy configuration
  template:
    src: templates/smb1.conf.j2
    dest: /etc/samba/smb1.conf
    mode: '0644'
    owner: root
    group: root
  notify: reload smb1
