system_os: rocky
system_os_version: 10
vm_vcpus: 2
vm_memory_mb: 2048
vm_volumes:
-  capacity: 20000M
bao_token_label: "{{ vault_bao_pkcs11_token_label }}"
bao_pkcs11_pin: "{{ vault_bao_pkcs11_pin }}"
bao_pkcs11_key_label: "{{ vault_bao_pkcs11_key_label }}"
bao_pkcs11_mechanism: "{{ vault_bao_pkcs11_mechanism }}"
bao_pkcs11_rsa_hash: "{{ vault_bao_pkcs11_rsa_hash }}"
